name: 🌐 Check URLs
on:
  push:
  pull_request:
  schedule:
    # Every Friday at 15:35 (UTC).
    # URLs can decay over time. Setting up a schedule makes it possible to be warned
    # about dead links as soon as possible.
    - cron: "35 15 * * FRI"

jobs:
  check-urls:
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@v4

      - name: Check link validity
        uses: lycheeverse/lychee-action@v2.4.0

      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}

      - name: Check npm packages manually
        run: |
          grep -oE 'https://www\.npmjs\.com/package/[a-zA-Z0-9@/._-]+' README.md | sort -u | while read -r url; do \
            echo -n "Checking $url... "; \
            result=$(curl -w "%{http_code} %{url_effective}" -L "$url" --http1.1 -s -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" -o /dev/null ); \
            status=$(echo $result | cut -d' ' -f1); final_url=$(echo $result | cut -d' ' -f2); \
            if [[ "$status" -eq 200 && ! "$final_url" == *"/login"* ]]; then
                echo "Found!"; \
            else
                result=$(echo "$result" | sed 's/200/404/'); \
                echo "Status code: $status"; exit 1; \
            fi
          done
